
--CONSULTA 1

--REALICE UNA CONSULTA QUE PERMITA LISTAR TODAS LAS CAPACITACIONES DE UN CLIENTE EN PARTICULAR, INDICANDO EL NOMBRE COMPLETO, LA EDAD Y EL CORREO ELECTRÓNICO DE LOS ASISTENTES.

SELECT  C.CLIENTE_RUTCLIENTE AS RUT_CLIENTE, C.IDCAPACITACION, C.CAPFECHA AS FECHA_CAPACITACION,TO_CHAR(C.CAPHORA,'HH24:MI') AS HORA_CAPACITACION, C.CAPLUGAR AS LUGAR_CAPACITACION, 
C.CAPDURACION AS DURACION_CAPACITACION, A.ASISTNOMBRECOMPLETO AS NOMBRE_COMPLETO_ASISTENTE, A.ASISTEDAD AS EDAD_ASISTENTE, A.ASISTCORREO AS CORREO_ASISTENTE FROM CAPACITACION C 
LEFT JOIN  ASISTENTES A ON A.CAPACITACION_IDCAPACITACION = C.IDCAPACITACION WHERE CLIENTE_RUTCLIENTE = 112549872;



--CONSULTA 2

--REALICE UNA CONSULTA QUE PERMITA DESPLEGAR TODAS LAS VISITAS EN TERRENO REALIZADAS A LOS CLIENTES QUE SEAN DE LA COMUNA DE VALPARAÍSO. POR CADA VISITA DEBE INDICAR 
--TODOS LOS CHEQUEOS QUE SE HICIERON EN ELLA, JUNTO CON EL ESTADO DE CUMPLIMIENTO DE CADA UNO.

SELECT D.RUTCLIENTE,D.CLICOMUNA, V.IDVISITA, V.VISFECHA, V.VISHORA, V.VISLUGAR, V.VISCOMENTARIOS, C.NOMBRECHEQUEO, F.CUMPLIMIENTO, F.OBSERVACIONES
FROM CLIENTE D, VISITA V, CHEQUEOS C, CHEQUEOVISITA F WHERE D.CLICOMUNA='VALPARAISO' AND D.RUTCLIENTE=V.CLIENTE_RUTCLIENTE AND V.IDVISITA = F.VISITA_IDVISITA AND C.IDCHEQUEO = F.CHEQUEOS_IDCHEQUEO
 


--CONSULTA 3

--REALICE UNA CONSULTA QUE DESPLIEGUE LOS ACCIDENTES REGISTRADOS PARA TODOS LOS CLIENTES, INDICANDO LOS DATOS DE DETALLE DEL ACCIDENTE, 
--Y EL NOMBRE, APELLIDO, RUT Y TELÉFONO DEL CLIENTE AL QUE SE ASOCIA DICHA SITUACIÓN.


SELECT A.ACCIDENTEID AS IDENTIFICADOR_ACCIDENTE, A.ACCIFECHA AS FECHA_ACCIDENTE, TO_CHAR(A.ACCIHORA,'HH24:MI') AS HORA_ACCIDENTE, A.ACCILUGAR AS LUGAR_ACCIDENTE,
A.ACCIORIGEN AS ORIGEN_ACCIDENTE, A.ACCICONSECUENCIA AS CONSECUENCIAS_ACCIDENTE, C.CLINOMBRES AS NOMBRE_CLIENTE, C.CLIAPELLIDOS AS APELLIDOS_CLIENTE, 
C.RUTCLIENTE AS RUT_CLIENTE, C.CLITELEFONO AS TELEFONO_CLIENTE FROM ACCIDENTE A LEFT JOIN CLIENTE C ON C.RUTCLIENTE=A.CLIENTE_RUTCLIENTE;
