
--CONSULTA 1

CREATE SEQUENCE SEQ_CLIENTES
START WITH 7
INCREMENT BY 1;


CREATE OR REPLACE TRIGGER  CLIENTE_TRI
BEFORE INSERT ON clientes
FOR EACH ROW
WHEN (new.idcliente IS NULL)
BEGIN
 SELECT SEQ_CLIENTES.NEXTVAL
 INTO :new.idcliente
 FROM dual;
END;
/

--CONSULTA 2

INSERT INTO CLIENTES VALUES ('Pablo','Marmol','Los Ojos #478',933557711);
INSERT INTO CLIENTES (IDCLIENTE,NOMBRES,APELLIDOS) VALUES ('lucas','Marambio');

--CONSULTA 3

ALTER TABLE VENTAS ADD CONSTRAINT CK_CANTARTICULOS CHECK (CANTARTICULOS IN (1,2,3,4,5));

