
--CONSULTA 1

SELECT * FROM capacitacion WHERE dia = 'LUNES' AND duracion < 90;

--CONSULTA 2

SELECT NOMBRES, RUTCLIENTE, LUGAR, DURACION FROM ASISTENTES, CAPACITACION WHERE ASISTENTES.CAPACITACION_IDCAPACITACION = CAPACITACION.IDCAPACITACION;

--CONSULTA 3

SELECT C.RUTCLIENTE, C.DIA, C.HORA, C.CANTIDADASISTENTES, COUNT (C.IDCAPACITACION) AS CONTAR_ASISTENTES FROM CAPACITACION C
LEFT JOIN ASISTENTES A ON A.CAPACITACION_IDCAPACITACION = c.idcapacitacion
GROUP BY  C.RUTCLIENTE, C.DIA, C.HORA, C.CANTIDADASISTENTES
HAVING C.CANTIDADASISTENTES != COUNT (C.IDCAPACITACION)

--CONSULTA 4

SELECT C.CANTIDADASISTENTES, C.LUGAR, C.DURACION, C.DIA, C.HORA FROM CAPACITACION C LEFT JOIN ASISTENTES A ON C.IDCAPACITACION =  A.CAPACITACION_IDCAPACITACION  WHERE c.cantidadasistentes > 3;

