
--CONSULTA 1

SELECT idventa, cantarticulos, clientes_idcliente, subtotal, impuesto, total, (SUBTOTAL + IMPUESTO) AS RESULTADO FROM VENTAS WHERE TOTAL <> (SUBTOTAL + IMPUESTO);

--CONSULTA 2

SELECT SUM(TOTAL) AS SUMA_TOTAL FROM VENTAS;

--CONSULTA 3

SELECT C.NOMBRES, C.APELLIDOS, V.IDVENTA, V.VENDEDOR, V.CANTARTICULOS, V.SUBTOTAL, V.IMPUESTO, V.TOTAL FROM CLIENTES C, VENTAS V 
WHERE NOMBRES = 'Antonia' AND APELLIDOS = 'Aranda'  AND CLIENTES_IDCLIENTE = '1';

--CONSULTA 4

SELECT IDCLIENTE, CONCAT (NOMBRES, APELLIDOS) FROM CLIENTES WHERE DIRECCION IS NULL;

--CONSULTA 5

SELECT MAX(TOTAL), MIN(TOTAL) FROM VENTAS;
