
--OCUPAMOS DELETE PODER MODIFICAR LOS CAMPOS, PUESTO QUE HABIA CAMPOS NUMERICOS
--Y NO PODIAN QUEDAR NULL ASI QUE SE OPTO POR ELIMINAR EL CONTENIDO DE LAS TABLAS

DELETE FROM DETALLEVENTA
DELETE FROM PRODUCTO
DELETE FROM VENTAS
DELETE FROM CLIENTES

-- ALTERAMOS LA TABLA DETALLEVENTA

ALTER TABLE DETALLEVENTA MODIFY VENTAS_IDVENTA NUMBER(6);


-- CREAMOS LA TABLA CATEGORIA

CREATE TABLE CATEGORIA (
IDCATEGORIA NUMBER(6) PRIMARY KEY,
NOMBRECATEGORIA VARCHAR2(75) NOT NULL);


-- ALTERAMOS LA TABLA PRODUCTO

ALTER TABLE PRODUCTO RENAME COLUMN NOMBREPROD TO NOMBREPRODUCTO;

ALTER TABLE PRODUCTO ADD CATEGORIA_IDCATEGORIA NUMBER(6)NOT NULL;

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY ( CATEGORIA_IDCATEGORIA ) REFERENCES CATEGORIA ( IDCATEGORIA );


-- ALTERAMOS LA TABLA CLIENTES

ALTER TABLE CLIENTES MODIFY IDCLIENTE NUMBER(9);
ALTER TABLE CLIENTES MODIFY TELEFONO VARCHAR2(50);


-- ALTERAMOS LA TABLA VENTAS

ALTER TABLE VENTAS MODIFY IDVENTA NUMBER(6);

ALTER TABLE VENTAS MODIFY VENDEDOR NOT NULL;

ALTER TABLE VENTAS MODIFY CANTARTICULOS NUMBER(3);

ALTER TABLE VENTAS MODIFY SUBTOTAL NUMBER(9);

ALTER TABLE VENTAS MODIFY IMPUESTO NUMBER(9);

ALTER TABLE VENTAS MODIFY TOTAL NUMBER(12);

ALTER TABLE VENTAS MODIFY CLIENTES_IDCLIENTE NUMBER(9);

