
-- CONSULTA 1

INSERT INTO CAPACITACION (RUTCLIENTE,LUGAR,DURACION) VALUES ('78102301-K','LA SERENA',55);

-- CONSULTA 2

COMMIT;


-- CONSULTA 3

SET AUTOCOMMIT 2

-- CONSULTA 4

INSERT INTO ASISTENTES (CAPACITACION_IDCAPACITACION,EDAD,NOMBRES) VALUES (1519,24,'Javier Concha');
INSERT INTO ASISTENTES (CAPACITACION_IDCAPACITACION,EDAD,NOMBRES) VALUES (1519,47,'Mauricio Torres');


-- CONSULTA 5

UPDATE CAPACITACION SET DIA = '10/03/2015', HORA = '23:59', CANTIDADASISTENTES = 1 WHERE IDCAPACITACION = 1519;

-- CONSULTA 6

DELETE FROM ASISTENTES WHERE capacitacion_idcapacitacion = 1519;

-- CONSULTA 7

ROLLBACK;
