
--CONSULTA 1

SELECT * FROM CLIENTES ORDER BY APELLIDOS DESC;

--CONSULTA 2

SELECT * FROM CLIENTES WHERE TELEFONO IS NOT NULL AND DIRECCION IS NULL;

--CONSULTA 3

SELECT IDCLIENTE, NOMBRES, APELLIDOS, IDVENTA, SUBTOTAL, TOTAL FROM CLIENTES, VENTAS;


--CONSULTA 4

SELECT IDCLIENTE, NOMBRES, APELLIDOS, TOTAL FROM CLIENTES, VENTAS WHERE IDCLIENTE=CLIENTES_IDCLIENTE;

