
--CONSULTA 1

ALTER TABLE AYUDAS ADD CONSTRAINT AYUDAID_PK PRIMARY KEY (AYUDAID);

--CONSULTA 2

ALTER TABLE AYUDAS ADD CONSTRAINT AYUDAS_LLAVE_FK FOREIGN KEY ( BENEFICIARIOID ) REFERENCES BENEFICIARIOS ( BENEFICIARIOID );

--CONSULTA 3

ALTER TABLE BENEFICIARIOS MODIFY NOMBRE VARCHAR2(75) NOT NULL;

--CONSULTA 4

ALTER TABLE BENEFICIARIOS ADD CONSTRAINT BENEFICIARIOS_LLAVE_FK FOREIGN KEY ( CIUDADID ) REFERENCES CIUDADES ( CIUDADID );

--CONSULTA 5

ALTER TABLE CIUDADES MODIFY NOMBRECIUDAD NOT NULL;
