
--CONSULTA 1

SELECT * FROM VENTAS WHERE IDVENTA BETWEEN 6 AND 14;

--CONSULTA 2

SELECT COMPRADOR,CANTARTICULOS FROM VENTAS WHERE VENDEDOR IS NULL;

--CONSULTA 3

SELECT * FROM VENTAS WHERE CANTARTICULOS > 5 AND IMPUESTO IS NULL;
