
--CREAMOS LA TABLA VISITA

CREATE TABLE VISITA (
IDVISITA NUMBER(9)PRIMARY KEY,
VISFECHA DATE NOT NULL,
VISHORA DATE, 
VISLUGAR VARCHAR2(50) NOT NULL,
VISCOMENTARIOS VARCHAR2 (250) NOT NULL,
CLIENTE_RUTCLIENTE NUMBER(9) NOT NULL
);

ALTER TABLE VISITA ADD CONSTRAINT VISITA_CLIENTE_FK FOREIGN KEY ( CLIENTE_RUTCLIENTE ) REFERENCES CLIENTE( RUTCLIENTE );

--MODIFICAMOS LA TABLA ACCIDENTE

ALTER TABLE ACCIDENTE RENAME COLUMN DIA TO ACCIFECHA;
ALTER TABLE ACCIDENTE MODIFY ACCIFECHA DATE NOT NULL;

ALTER TABLE ACCIDENTE RENAME COLUMN HORA TO ACCIHORA;
ALTER TABLE ACCIDENTE MODIFY ACCIHORA DATE NOT NULL;

ALTER TABLE ACCIDENTE RENAME COLUMN LUGAR TO ACCILUGAR;
ALTER TABLE ACCIDENTE MODIFY ACCILUGAR VARCHAR2(150);

ALTER TABLE ACCIDENTE RENAME COLUMN ORIGEN TO ACCIORIGEN;
ALTER TABLE ACCIDENTE MODIFY ACCIORIGEN NOT NULL;

ALTER TABLE ACCIDENTE RENAME COLUMN CONSECUENCIAS TO ACCICONSECUENCIA;


--MODIFICAMOS LA TABLA ASISTENTES

ALTER TABLE ASISTENTES RENAME COLUMN NOMBRES TO ASISTNOMBRECOMPLETO;

ALTER TABLE ASISTENTES RENAME COLUMN EDAD TO ASISTEDAD;

ALTER TABLE ASISTENTES DROP COLUMN CAPACITACION_IDCAPACITACION;

ALTER TABLE ASISTENTES ADD ASISTCORREO VARCHAR2(70);

ALTER TABLE ASISTENTES ADD ASISTTELEFONO VARCHAR2(20);

ALTER TABLE ASISTENTES ADD CAPACITACION_IDCAPACITACION NUMBER(9) NOT NULL;

ALTER TABLE ASISTENTES ADD CONSTRAINT ASISTENTES_CAPACITACION_FK FOREIGN KEY ( CAPACITACION_IDCAPACITACION ) REFERENCES CAPACITACION ( IDCAPACITACION );



--MODIFICAMOS LA TABLA CAPACITACION

ALTER TABLE CAPACITACION RENAME COLUMN FECHA TO CAPFECHA;
ALTER TABLE CAPACITACION MODIFY CAPFECHA NOT NULL;

ALTER TABLE CAPACITACION RENAME COLUMN HORA TO CAPHORA;

ALTER TABLE CAPACITACION RENAME COLUMN LUGAR TO CAPLUGAR;
ALTER TABLE CAPACITACION MODIFY CAPLUGAR VARCHAR2(100);

ALTER TABLE CAPACITACION RENAME COLUMN DURACION TO CAPDURACION;
ALTER TABLE CAPACITACION MODIFY CAPDURACION NUMBER(4);

ALTER TABLE CAPACITACION DROP COLUMN CANTIDADASISTENTES;


--MODIFICAMOS LA TABLA CLIENTE

ALTER TABLE CLIENTE RENAME COLUMN NOMBRES TO CLINOMBRES;

ALTER TABLE CLIENTE RENAME COLUMN APELLIDOS TO CLIAPELLIDOS;
ALTER TABLE CLIENTE MODIFY CLIAPELLIDOS VARCHAR2(50);

ALTER TABLE CLIENTE RENAME COLUMN TELEFONO TO CLITELEFONO;

ALTER TABLE CLIENTE RENAME COLUMN AFP TO CLIAFP;

ALTER TABLE CLIENTE RENAME COLUMN SISTEMASALUD TO CLISISTEMASALUD;

ALTER TABLE CLIENTE RENAME COLUMN DIRECCION TO CLIDIRECCION;
ALTER TABLE CLIENTE MODIFY CLIDIRECCION VARCHAR2(100) NOT NULL;

ALTER TABLE CLIENTE RENAME COLUMN COMUNA TO CLICOMUNA;
ALTER TABLE CLIENTE MODIFY CLICOMUNA NOT NULL;

ALTER TABLE CLIENTE RENAME COLUMN EDAD TO CLIEDAD;
